version: '2.2'
services:
  app:
    container_name: contenedor_python
    build:
      context: .  # Usa el Dockerfile en la carpeta actual
      dockerfile: Dockerfile
    image: prueba:1  # Esto permite que la imagen se etiquete correctamente
    restart: always
    environment:
      NAME: ${NAME}
      USER: ${USER}
      PASSWORD: ${PASS}
      HOST: basededatos
      DJ_USER: ${DJ_USER}
      DJ_PASSWORD: ${DJ_PASSWORD}
      DJ_EMAIL: ${DJ_EMAIL}
      URL: ${URL}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: basededatos
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${NAME}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASS}
      MYSQL_ROOT_PASSWORD: ${ROOT}
    volumes:
      - mariadb_data1:/var/lib/mysql

volumes:
  mariadb_data1:

